version: '3'

services:
  exhauster-monitoring-ui:
    build:
      context: frontend
      dockerfile: DockerfileFrontend
    restart: always
    container_name: exhauster-monitoring-ui
    ports:
      - "80:80"
    tty: true

  exhauster-monitoring-api:
    image: docker.io/library/exhauster-monitoring:1.0.0
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dconfig.file=/workspace/application.properties", "-jar", "exhauster-monitoring:1.0.0.jar"]
    restart: always
    volumes:
      - './backend/src/main/resources/application.properties:/workspace/application.properties'
    container_name: exhauster-monitoring-api
    ports:
      - "38080:8080"
    environment:
      - MONGODB_HOST=mongodb-primary
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=metrics
      - MONGODB_USER=mongo
      - MONGODB_PASS=mongo
    tty: true

  mongodb-primary:
    image: docker.io/bitnami/mongodb:6.0
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_ROOT_USERNAME=mongoadm
      - MONGODB_ROOT_PASSWORD=mongoadm
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=metrics
    ports:
      - "37017:27017"

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_USERNAME=mongoadm
      - MONGODB_PRIMARY_ROOT_PASSWORD=mongoadm

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=mongoadm
      - MONGODB_REPLICA_SET_KEY=123456789

#  grafana:
#    build: './backend/monitoring/config/grafana'
#    container_name: grafana
#    ports:
#      - "33000:3000"
##    volumes:
##      - ./backend/monitoring/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  mongodb_data:
    driver: local