### Создание уведомления
# @no-log
POST http://localhost:8080/api/v1/notifications?projection=notificationInfo
Content-Type: application/json

{
  "exhausterId": "1",
  "partId": "Подшипник #3",
  "notificationType": "BROKEN",
  "description": "Деталь сломана - треубется замена."
}

### Получение всех уведомлений
# @no-log
GET http://localhost:8080/api/v1/notifications?projection=notificationInfo
Content-Type: application/json

### Получение уведомления по UUID
# @no-log
GET http://localhost:8080/api/v1/notifications/1c69faf7-33fb-4201-bf6e-909f1a0d4bc0?projection=notificationInfo
Content-Type: application/json

### Изменение уведомления по UUID
# @no-log
PATCH http://localhost:8080/api/v1/notifications/1c69faf7-33fb-4201-bf6e-909f1a0d4bc0?projection=notificationInfo
Content-Type: application/json

{
  "notificationType": "OVERHEATED"
}

### Удаление уведомления по UUID
# @no-log
DELETE http://localhost:8080/api/v1/notifications/1c69faf7-33fb-4201-bf6e-909f1a0d4bc0
